### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by TheDiamondYT1** [byteandahalf/byteandahalf.github.io#3]
You need an index.html for this to work

**Comment by byteandahalf** [comment]
Well f*ck.

**Comment by byteandahalf** [comment]
Fix it, you now have write access.

**Comment by TheDiamondYT1** [comment]
Quick question before I go to school: why did you add an alt.xml

**Comment by TheDiamondYT1** [comment]
You also need a gh-pages branch. Making it now.

**Comment by TheDiamondYT1** [comment]
Nvm you don't need it. I added a test index to the master branch. The website now works. However I'm not sure how you will make the contents from alt.XML display.
